-- INSERT INTO company(id, company_name)
-- VALUES (1, 'OOCL');
--
-- INSERT INTO employee(id, name, age, gender, company_id)
-- VALUES (1, 'Bob Smith', 20, 'Male', 1);
-- INSERT INTO employee(id, name, age, gender, company_id)
-- VALUES (2, 'Tom Green', 20, 'Female', 1);
-- INSERT INTO employee(id, name, age, gender, company_id)
-- VALUES (3, 'Will Smith', 50, 'Male', 1);
