spring:
  redis:
#   database index
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
    #   connection pool max connection
        max-active: 8
        max-wait: -1
