spring:
  datasource:
    url: jdbc:h2:mem:demo
    #    url: jdbc:h2:file:~/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
    schema: init_schema.sql
    data: init_data.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:.enabled: true
